export const sellingPointsOne = [
  "50 Configurable Products",
  "1 User",
  "1 Restaurant Location",
  "1 Personal Web Developer",
  "1 Impact Printer",
  "Mobile Ordering",
  "Unlimited Content Revisions",
  "Customer Purchasing Analytics",
  "Coupon Functionality",
  "Custom Business Newsletter",
  "Guest Checkout",
  "Product Recommendations",
  "Customer Reviews",
  "Saved Payment Methods",
  "Cross Sells / Upsells",
  "Customer Information Encryption",
  "24/7 Tech Support",
  "Continual Website Backups",
  "Security Patches",
  "Money Back Guarantee",
  "Satisfaction Guaranteed",
  "DFY Maintenance Package",
];

export const sellingPointsTwo = [
  "100 Configurable Products",
  "3 Users",
  "3 Restaurant Locations",
  "2 Personal Web Developers",
  "Professional Product Photographs",
  "Employee Affiliate Program",
  "Multiple Languages",
  "*ALL STANDARD PACKAGE FEATURES*",
];

export const sellingPointsThree = [
  "Unlimited Products",
  "Unlimited Users",
  "Unlimited Restaurant Locations",
  "Web Development Team",
  "Curbside Delivery Tracking",
  "Customer Loyalty Program",
  "SEO Optimization",
  "Existing POS Integration (if available)",
  "*ALL ELITE PACKAGE FEATURES*",
];
