export const sellingPointsOne = [
  "50 Configurable Products",
  "1 User",
  "1 Restaurant Location",
  "Mobile Ordering",
  "Unlimited Content Revisions",
  "24/7 Tech Support",
  "Customer Purchasing Analytics",
  "Coupon Functionality",
  "Custom Business Newsletter",
  "Guest Checkout",
  "Product Recommendations",
  "Customer Reviews",
  "Saved Payment Methods",
  "Cross Sells / Upsells",
  "Continual Website Backups",
  "Customer Information Encryption",
  "Security Patches",
  "Money Back Guarantee",
  "Satisfaction Guaranteed",
  "DFY Maintenance Package",
  "Existing POS Integration (if available)",
];

export const sellingPointsTwo = [
  "100 Configurable Products",
  "3 Users",
  "3 Restaurant Locations",
  "Professional Product Photographs",
  "Employee Affiliate Program",
  "Multiple Languages",
  "*ALL STANDARD PACKAGE FEATURES*",
];

export const sellingPointsThree = [
  "Unlimited Products",
  "Unlimited Users",
  "Unlimited Restaurant Locations",
  "Mobile Order Delivery",
  "Curbside Delivery Tracking",
  "Customer Loyalty Program",
  "SEO Optimization",
  "QuickBooks Integration",
  "Full Page Caching",
  "*ALL ELITE PACKAGE FEATURES*",
];
