export const sellingPointsOne = [
  "25 Configurable Products",
  "1 Administrative User",
  "1 Restaurant Location",
  "1 Personal Web Developer",
  "1 Thermal Printer",
  "Mobile Ordering",
  "Unlimited Content Revisions",
  "Customer Purchasing Analytics",
  "Coupon Functionality",
  "Custom Business Newsletter",
  "Guest Checkout",
  "Product Recommendations",
  "Customer Reviews",
  "Saved Payment Methods",
  "Cross Sells / Upsells",
  "Customer Information Encryption",
  "Full Page Caching",
  "24/7 Tech Support",
  "Continual Website Backups",
  "Security Patches",
  "Money Back Guarantee",
  "Satisfaction Guaranteed",
  "DFY Maintenance Package",
];

export const sellingPointsTwo = [
  "50 Configurable Products",
  "3 Administritive Users",
  "2 Restaurant Locations",
  "2 Personal Web Developers",
  "Professional Product Photographs",
  "Employee Affiliate Program",
  "Multiple Languages",
  "*ALL STANDARD PACKAGE FEATURES*",
];

export const sellingPointsThree = [
  "100 Configurable Products",
  "5 Administrative Users",
  "5 Restaurant Locations",
  "3 Personal Web Developers",
  "Curbside Delivery Tracking",
  "Customer Loyalty Program",
  "SEO Optimization",
  "Existing POS Integration (if available)",
  "*ALL ELITE PACKAGE FEATURES*",
];
